name: Ansible

on:
  push:
    paths:
      - 'ansible/**'

jobs:
  ansible:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ansible
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

      - name: Install Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip jq
          pip3 install --user ansible
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fetch SSH private key from Secrets Manager
        env:
          PROJECT: infra-docker-project
        run: |
          PREFIX="${PROJECT}-ec2-ssh-private-key"
          SECRET_NAME=$(aws secretsmanager list-secrets \
            --filters Key=name,Values="$PREFIX" \
            --query 'SecretList | sort_by(@,&CreatedDate) | [-1].Name' --output text)
          if [ "$SECRET_NAME" = "None" ] || [ -z "$SECRET_NAME" ]; then
            echo "No secret found with prefix $PREFIX" >&2
            exit 1
          fi
          aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text > id_rsa
          chmod 600 id_rsa

      - name: Build dynamic inventory from EC2 instances
        env:
          PROJECT: infra-docker-project
        run: |
          mkdir -p inventory
          IPS=$(aws ec2 describe-instances \
            --filters "Name=tag:Project,Values=${PROJECT}" "Name=instance-state-name,Values=running" \
            --query 'Reservations[].Instances[].PublicIpAddress' --output text)
          echo "[web]" > inventory/inventory.ini
          for ip in $IPS; do echo "$ip" >> inventory/inventory.ini; done
          echo "Inventory:" && cat inventory/inventory.ini

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible --version
          ansible-playbook -i inventory/inventory.ini playbook.yml \
            -u ec2-user \
            --private-key ./id_rsa


